# By Abdullah As-Sadeed

name: bitscoper_cyberkit
description: A Flutter application offering IPv4 Subnet Scanner, mDNS Scanner, TCP Port Scanner, Route Tracer, Pinger, File Hash Calculator, String Hash Calculator, CVSS Calculator, Base Encoder, Morse Code Translator, QR Code Generator, Open Graph Protocol Data Extractor, Series URI Crawler, DNS Record Retriever, WHOIS Retriever, and Wi-Fi Information Viewer.
publish_to: none
version: 16.0.0+34

environment:
  sdk: ">=3.9.0"

dependencies:
  async: any
  b: null
  connectivity_plus: null
  crypto: null
  cvss_vulnerability_scoring: null
  dart_ping: null
  dart_ping_ios: null
  dnsolve: null
  file_picker: null
  flutter:
    sdk: flutter
  flutter_colorpicker: null
  flutter_local_notifications: null
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: null
  flutter_staggered_grid_view: null
  flutter_traceroute:
    git:
      url: https://github.com/Koizeay/flutter_traceroute.git
  google_fonts: null
  html: null
  http: null
  intl: any
  morse_code_translator: null
  network_info_plus: null
  network_tools_flutter: 2.0.7 # Locked due to Two Call Stacks Being "Paused on Entry"
  ogp_data_extract: null
  package_info_plus: null
  path_provider: null
  permission_handler: null
  qr_flutter: null
  quick_actions: null
  tcp_scanner: null
  timelines_plus: null
  url_launcher: null
  uuid: null
  whois: null
  yaml: null

dev_dependencies:
  dashmon: null
  flutter_launcher_icons: null
  flutter_lints: null
  flutter_test:
    sdk: flutter
  msix: null
  rename: null

flutter:
  assets:
    - assets/
    - assets/icon/
  generate: true
  uses-material-design: true

flutter_launcher_icons:
  image_path: assets/icon/maskable_icon_x512.png
  android: true
  min_sdk_android: 30
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/icon/maskable_icon_x512.png
  macos:
    generate: true
    image_path: assets/icon/maskable_icon_x512.png
  ios: true
  remove_alpha_ios: true
  windows:
    generate: true
    image_path: assets/icon/icon.png
    icon_size: 192
  web:
    generate: true
    image_path: assets/icon/icon.png
    background_color: "#F0F8FF"
    theme_color: "#424242"

flutter_native_splash:
  color: "#F0F8FF"
  image: assets/icon/icon.png
  branding: assets/branding.png
  branding_mode: bottom
  color_dark: "#F0F8FF"
  image_dark: assets/icon/icon.png
  branding_dark: assets/branding.png
  android_gravity: center
  ios_content_mode: center
  web_image_mode: center

msix_config:
  display_name: Bitscoper CyberKit
  identity_name: 18862TeleChirkut.BitscoperCyberKit
  publisher_display_name: Bitscoper
  publisher: CN=37755377-8C56-44E3-8D7A-0F1AD45034D2
  logo_path: assets/icon/maskable_icon_x512.png
  trim_logo: false
  languages: en-US
  execution_alias: Bitscoper_CyberKit
  enable_at_startup: false
  capabilities:
    internetClient, internetClientServer, privateNetworkClientServer,
    removableStorage, wiFiControl
  architecture: x64
  store: true
  build_windows: true
  windows_build_args: --release --obfuscate --split-debug-info=./build/Debug_Symbols/Windows/
  debug: false
  msix_version: 16.0.0.0
  output_name: Bitscoper_CyberKit
