# By Abdullah As-Sadeed

name: bitscoper_cyberkit
description: A Flutter application offering Bluetooth Low Energy Scanner, IPv4 Subnet Scanner, mDNS Scanner, UPnP Scanner, Route Tracer, TCP Port Scanner, Pinger, DNS Record Retriever, File Hash Calculator, String Hash Calculator, Base Encoder, Series URI Crawler, OGP Data Extractor, WHOIS Retriever, CVSS Calculator, Morse Code Translator, and Wi-Fi Details Viewer.
version: 18.2.0+42
publish_to: none

environment:
  sdk: ">=3.13.0"
  flutter: ">=3.47.0"

dependencies:
  b: ^0.2.0
  connectivity_plus: ^7.3.1
  crypto: ^3.0.7
  cvss_vulnerability_scoring: ^1.0.0
  dart_ping: ^10.0.1 # !Web
  dns_client: ^1.3.1 # !Web
  file_picker: ^12.1.1
  flutter:
    sdk: flutter
  flutter_blue_plus: ^2.3.12
  flutter_local_notifications: ^22.3.0 # !Web
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.8 # !Linux !maxOS !Windows
  flutter_riverpod: ^3.4.2
  flutter_staggered_grid_view: ^0.7.0
  flutter_traceroute:
    git:
      url: https://github.com/bitscoper/flutter_traceroute.git # !Linux !macOS !Windows !Web
  http: ^1.6.0
  intl: ^0.20.3
  morse_code_translator: ^0.0.1
  multicast_dns: ^0.3.3+1 # !Web
  network_info_plus: ^8.2.1
  ogp_data_extract: ^0.2.2
  package_info_plus: ^10.2.1
  permission_guard: ^2.0.1 # !Linux # !macOS
  quick_actions: ^1.1.0 # !Linux !macOS !Windows !Web
  shared_preferences: ^2.5.5
  tcp_scanner: ^2.0.5 # !Web
  timelines_plus: ^2.0.1
  upnp_client: ^1.5.0 # !Web
  url_launcher: ^6.3.2
  uuid: ^4.6.0
  whois: ^1.0.0 # !Web
  yaml: ^3.1.3

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  msix: ^3.18.0
  rename: ^3.1.0

flutter:
  assets:
    - assets/
    - assets/icon/
  generate: true
  uses-material-design: true

flutter_launcher_icons:
  image_path: assets/icon/square_whiteBackground_25percentPadding_colored_512x512.png

  android: true
  min_sdk_android: 24
  image_path_android: assets/icon/square_whiteBackground_25percentPadding_colored_512x512.png
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground_inset: 25
  adaptive_icon_foreground: assets/icon/square_transparent_unpadded_colored_512x512.png
  adaptive_icon_monochrome: assets/icon/square_transparent_unpadded_monochrome_512x512.png

  macos:
    generate: true
    image_path: assets/icon/square_whiteBackground_25percentPadding_colored_512x512.png

  ios: true
  remove_alpha_ios: true
  background_color_ios: "#FFFFFF"
  image_path_ios: assets/icon/square_transparent_unpadded_colored_512x512.png
  image_path_ios_dark_transparent: assets/icon/square_transparent_unpadded_colored_512x512.png
  image_path_ios_tinted_grayscale: assets/icon/square_transparent_unpadded_greyscale_512x512.png
  desaturate_tinted_to_grayscale_ios: true

  windows:
    generate: true
    image_path: assets/icon/square_whiteBackground_25percentPadding_colored_256x256.png
    icon_size: 256

  web:
    generate: true
    image_path: assets/icon/square_whiteBackground_25percentPadding_colored_512x512.png
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"

flutter_native_splash:
  fullscreen: true
  color: "#FFFFFF"
  image: assets/icon/square_transparent_unpadded_colored_512x512.png
  color_dark: "#FFFFFF"
  image_dark: assets/icon/square_transparent_unpadded_colored_512x512.png

  android: true
  android_min_sdk: 24
  android_screen_orientation: user
  android_gravity: center

  color_android: "#FFFFFF"
  image_android: assets/icon/square_transparent_unpadded_colored_512x512.png
  color_dark_android: "#FFFFFF"
  image_dark_android: assets/icon/square_transparent_unpadded_colored_512x512.png

  android_12:
    color: "#FFFFFF"
    icon_background_color: "#FFFFFF"
    image: assets/icon/square_whiteBackground_35percentPadding_colored_1152x1152.png

    color_dark: "#FFFFFF"
    icon_background_color_dark: "#FFFFFF"
    image_dark: assets/icon/square_whiteBackground_35percentPadding_colored_1152x1152.png

  ios: true
  ios_content_mode: center

  color_ios: "#FFFFFF"
  image_ios: assets/icon/square_transparent_unpadded_colored_512x512.png
  color_dark_ios: "#FFFFFF"
  image_dark_ios: assets/icon/square_transparent_unpadded_colored_512x512.png

  web: true
  web_image_mode: center

  color_web: "#FFFFFF"
  image_web: assets/icon/square_transparent_unpadded_colored_512x512.png
  color_dark_web: "#FFFFFF"
  image_dark_web: assets/icon/square_transparent_unpadded_colored_512x512.png

msix_config:
  display_name: Bitscoper CyberKit
  identity_name: 18862TeleChirkut.BitscoperCyberKit
  publisher_display_name: bitscoper
  publisher: CN=37755377-8C56-44E3-8D7A-0F1AD45034D2
  logo_path: assets/icon/square_whiteBackground_25percentPadding_colored_512x512.png
  trim_logo: false
  languages: en-US
  execution_alias: Bitscoper_CyberKit
  enable_at_startup: false
  capabilities:
    internetClient, internetClientServer, privateNetworkClientServer,
    removableStorage, wiFiControl
  architecture: x64
  store: true
  build_windows: true
  windows_build_args: --release
  debug: false
  msix_version: 18.2.0.0
  output_name: Bitscoper_CyberKit
